// Lista completa de personajes de Super Smash Bros Ultimate
export const SSBU_CHARACTERS = [
  { id: 'mario', name: 'Mario', number: 1 },
  { id: 'donkey-kong', name: 'Donkey Kong', number: 2 },
  { id: 'link', name: 'Link', number: 3 },
  { id: 'samus', name: 'Samus', number: 4 },
  { id: 'dark-samus', name: 'Dark Samus', number: 4 },
  { id: 'yoshi', name: 'Yoshi', number: 5 },
  { id: 'kirby', name: 'Kirby', number: 6 },
  { id: 'fox', name: 'Fox', number: 7 },
  { id: 'pikachu', name: 'Pikachu', number: 8 },
  { id: 'luigi', name: 'Luigi', number: 9 },
  { id: 'ness', name: 'Ness', number: 10 },
  { id: 'captain-falcon', name: 'Captain Falcon', number: 11 },
  { id: 'jigglypuff', name: 'Jigglypuff', number: 12 },
  { id: 'peach', name: 'Peach', number: 13 },
  { id: 'daisy', name: 'Daisy', number: 13 },
  { id: 'bowser', name: 'Bowser', number: 14 },
  { id: 'ice-climbers', name: 'Ice Climbers', number: 15 },
  { id: 'sheik', name: 'Sheik', number: 16 },
  { id: 'zelda', name: 'Zelda', number: 17 },
  { id: 'dr-mario', name: 'Dr. Mario', number: 18 },
  { id: 'pichu', name: 'Pichu', number: 19 },
  { id: 'falco', name: 'Falco', number: 20 },
  { id: 'marth', name: 'Marth', number: 21 },
  { id: 'lucina', name: 'Lucina', number: 21 },
  { id: 'young-link', name: 'Young Link', number: 22 },
  { id: 'ganondorf', name: 'Ganondorf', number: 23 },
  { id: 'mewtwo', name: 'Mewtwo', number: 24 },
  { id: 'roy', name: 'Roy', number: 25 },
  { id: 'chrom', name: 'Chrom', number: 25 },
  { id: 'mr-game-watch', name: 'Mr. Game & Watch', number: 26 },
  { id: 'meta-knight', name: 'Meta Knight', number: 27 },
  { id: 'pit', name: 'Pit', number: 28 },
  { id: 'dark-pit', name: 'Dark Pit', number: 28 },
  { id: 'zero-suit-samus', name: 'Zero Suit Samus', number: 29 },
  { id: 'wario', name: 'Wario', number: 30 },
  { id: 'snake', name: 'Snake', number: 31 },
  { id: 'ike', name: 'Ike', number: 32 },
  { id: 'pokemon-trainer', name: 'Pokemon Trainer', number: 33 },
  { id: 'diddy-kong', name: 'Diddy Kong', number: 36 },
  { id: 'lucas', name: 'Lucas', number: 37 },
  { id: 'sonic', name: 'Sonic', number: 38 },
  { id: 'king-dedede', name: 'King Dedede', number: 39 },
  { id: 'olimar', name: 'Olimar', number: 40 },
  { id: 'lucario', name: 'Lucario', number: 41 },
  { id: 'rob', name: 'R.O.B.', number: 42 },
  { id: 'toon-link', name: 'Toon Link', number: 43 },
  { id: 'wolf', name: 'Wolf', number: 44 },
  { id: 'villager', name: 'Villager', number: 45 },
  { id: 'mega-man', name: 'Mega Man', number: 46 },
  { id: 'wii-fit-trainer', name: 'Wii Fit Trainer', number: 47 },
  { id: 'rosalina-luma', name: 'Rosalina & Luma', number: 48 },
  { id: 'little-mac', name: 'Little Mac', number: 49 },
  { id: 'greninja', name: 'Greninja', number: 50 },
  { id: 'palutena', name: 'Palutena', number: 54 },
  { id: 'pac-man', name: 'Pac-Man', number: 55 },
  { id: 'robin', name: 'Robin', number: 56 },
  { id: 'shulk', name: 'Shulk', number: 57 },
  { id: 'bowser-jr', name: 'Bowser Jr.', number: 58 },
  { id: 'duck-hunt', name: 'Duck Hunt', number: 59 },
  { id: 'ryu', name: 'Ryu', number: 60 },
  { id: 'ken', name: 'Ken', number: 60 },
  { id: 'cloud', name: 'Cloud', number: 61 },
  { id: 'corrin', name: 'Corrin', number: 62 },
  { id: 'bayonetta', name: 'Bayonetta', number: 63 },
  { id: 'inkling', name: 'Inkling', number: 64 },
  { id: 'ridley', name: 'Ridley', number: 65 },
  { id: 'simon', name: 'Simon', number: 66 },
  { id: 'richter', name: 'Richter', number: 66 },
  { id: 'king-k-rool', name: 'King K. Rool', number: 67 },
  { id: 'isabelle', name: 'Isabelle', number: 68 },
  { id: 'incineroar', name: 'Incineroar', number: 69 },
  { id: 'piranha-plant', name: 'Piranha Plant', number: 70 },
  { id: 'joker', name: 'Joker', number: 71 },
  { id: 'hero', name: 'Hero', number: 72 },
  { id: 'banjo-kazooie', name: 'Banjo & Kazooie', number: 73 },
  { id: 'terry', name: 'Terry', number: 74 },
  { id: 'byleth', name: 'Byleth', number: 75 },
  { id: 'min-min', name: 'Min Min', number: 76 },
  { id: 'steve', name: 'Steve', number: 77 },
  { id: 'sephiroth', name: 'Sephiroth', number: 78 },
  { id: 'pyra-mythra', name: 'Pyra / Mythra', number: 79 },
  { id: 'kazuya', name: 'Kazuya', number: 80 },
  { id: 'sora', name: 'Sora', number: 81 },
  { id: 'mii-brawler', name: 'Mii Brawler', number: 51 },
  { id: 'mii-swordfighter', name: 'Mii Swordfighter', number: 52 },
  { id: 'mii-gunner', name: 'Mii Gunner', number: 53 }
].sort((a, b) => a.number - b.number)

export function getCharacterIcon(characterId: string): string {
  // URL de los iconos oficiales de Smash Ultimate
  return `https://www.smashbros.com/assets_v2/img/fighter/thumb_a/${characterId}.png`
}

export function getCharacterImage(characterId: string): string {
  // URL de las imágenes oficiales de Smash Ultimate
  return `https://www.smashbros.com/assets_v2/img/fighter/${characterId}/main.png`
}
